### ISSUE TITLE
Simpler io.Reader interface

### ISSUE THREAD

**Issue by klauspost** [cosnicolaou/pbzip2#3]
Would it be possible to create an interface that hides some of the complexity, so I can do:

```
dec, err := NewDecoder(io.Reader, options...)
defer dec.Close()
// Now just read data...
io.Copy(ioutil.Discard, dec)
```

It is not really obvious how to use your nice package.

**Comment by cosnicolaou** [comment]
Let me look at this later today.

**Comment by cosnicolaou** [comment]
FYI, I have this working now and will send you a PR tomorrow. It's tricky under the covers but the API is simple.

**Comment by klauspost** [comment]
Looks good. Tests work out.

**Comment by klauspost** [comment]
Implemented as https://github.com/minio/minio/pull/13360 - nice solid speedup.
