### ISSUE TITLE
Is that memory leak or my mistake?

### ISSUE THREAD

**Issue by middaysan** [cosnicolaou/pbzip2#32]
Hi maintainers,

I've been using your library in a API for parallel decompression of .tar.bz2 archives. I have noticed a significant memory leak when running my application on Linux, especially when the API endpoint that uses this functionality gets called repeatedly. However, the same application runs fine on macOS.

Here is version of my function that triggers the issue:

```golang
func unBzip2(sourcefile, dest string) error {
	reader, err := os.Open(sourcefile)
	if err != nil {
		return err
	}
	defer reader.Close()

	bzReader := pbzip2.NewReader(context.Background(), reader)
	var tarReader *tar.Reader = tar.NewReader(bzReader)

	filePath := ""
	var writer *os.File
        var header *tar.Header

	for {
		header, err = tarReader.Next()
		if err != nil {
			if err == io.EOF {
                                 err = nil
				break
			}
			return err
		}

		filePath = filepath.Join(dest, header.Name)

		switch header.Typeflag {
		case tar.TypeDir:
			err = os.MkdirAll(filePath, os.FileMode(header.Mode))
		case tar.TypeReg, tar.TypeRegA:
			writer, err = os.Create(filePath)
			if err == nil {
				_, err = io.Copy(writer, tarReader)
				if err != nil {
					log.Errorf("UNBZIP2: copy archieve's file error: %s \n", err)
					writer.Close()
					return err
				}
				writer.Close()

				err = os.Chmod(filePath, os.FileMode(header.Mode))
				if err != nil {
					return err
				}
			}
		default:
			log.Errorf("UNBZIP2: provider: Unable to untar type: %c in file %s\n", header.Typeflag, filePath)
			err = errors.New("provider: Unable to untar type file" + filePath)
		}

		if err != nil {
			log.Errorf("UNBZIP2: unpack file error: %s", err)
		}
	}

	return err
}
```

This function reads a .tar.bz2 file, then writes the contained files to disk. When running on Linux, the memory usage keeps growing, indicating a possible memory leak. 

Here debug graph of my app:
<img width="655" alt="Снимок экрана 2023-06-01 в 12 55 50" src="https://github.com/cosnicolaou/pbzip2/assets/36412453/e09f2ed8-6f5b-4da7-817a-9694f3982846">

I've done my best to ensure the correct usage of your library, closing resources where appropriate. I suspect the issue might be with pbzip2.NewReader but am unable to identify it exactly.

Maybe I do something wrong =(
I tried to call GC before and after unBzip2() function but it keeps growing exact in this function.

Any insights or suggestions you could provide would be greatly appreciated. Thank you in advance!

Best regards

**Comment by klauspost** [comment]
How does it work when you provide a proper context?

```Go
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	bzReader := pbzip2.NewReader(ctx, reader)
```

**Comment by middaysan** [comment]
I tried this, and no differences 😞 
<img width="641" alt="Снимок экрана 2023-06-01 в 13 59 35" src="https://github.com/cosnicolaou/pbzip2/assets/36412453/2d2a8c5a-b84c-408a-a8d7-5feb8d7b881c">

**Comment by middaysan** [comment]
More details, I run this app on next OS:

```
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.9"
```

And as I said on macOS app works fine

**Comment by middaysan** [comment]
I use https://go.dev/blog/pprof for debugging
<img width="676" alt="Снимок экрана 2023-06-01 в 15 30 00" src="https://github.com/cosnicolaou/pbzip2/assets/36412453/bc792187-9f4e-47c1-b026-9cab818e44ae">

**Comment by middaysan** [comment]
I've forgot add Golang version and library version, sorry

Golang 1.18
pbzip2 1.0.2

**Comment by klauspost** [comment]
Yes, but is it `alloc_space` or `inuse_space`? I guess if you attach the profile here we can see for ourselves if you are unsure.

**Comment by klauspost** [comment]
OK. There are about 220 blocks in flight or queued.

You can try to use a global pool for all your readers:

```Go
// Limit to 32 concurrent global operations.
var processPool = make(chan struct{}, 32)

func unBzip2(sourcefile, dest string) error {
	reader, err := os.Open(sourcefile)
	if err != nil {
		return err
	}
	defer reader.Close()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	bzReader := pbzip2.NewReader(ctx, reader, pbzip2.BZConcurrencyPool(processPool))
	var tarReader *tar.Reader = tar.NewReader(bzReader)
```

**Comment by middaysan** [comment]
<img width="1082" alt="Снимок экрана 2023-06-01 в 17 02 52" src="https://github.com/cosnicolaou/pbzip2/assets/36412453/f947479b-1d1e-42ff-a590-d0b62c7d06ab">

I have problem with this

**Comment by klauspost** [comment]
A, forgot the syntax. You have to wrap it in `DecompressionOptions(...)`

**Comment by middaysan** [comment]
Any ideas? :)

**Comment by cosnicolaou** [comment]
Sorry, which commit did you revert to? The example code above isn't quite correct since the pool needs to be primed. If you can create it as follows - it just primes the channels with tokens at the outset.

```
processPool = pbzip2.CreateConcurrencyPool(4) //  4 concurrent compressors
```

**Comment by middaysan** [comment]
I apologize for any confusion - my previous message was unclear. I rolled back a commit in my project that included @klauspost's suggestions, my project can't work with that suggestions.


`processPool = pbzip2.CreateConcurrencyPool(4) //  4 concurrent compressors`

With this suggestion I unpacked 5 archives and I have debug profile(see below)
[profile-2.pb.gz](https://github.com/cosnicolaou/pbzip2/files/11662354/profile-2.pb.gz)

If the memory consumption doesn't continuously increase with this solution, it would be quite satisfactory for me.
However, I will only be able to confirm this after a certain period of time, because I can test it only on server where I have Gentoo.

**Comment by klauspost** [comment]
@cosnicolaou Since he is seeing it lock up (to my understanding), my guess is that it is struct when all data haven't been read from the output, but it just stops. Maybe that can help repro.

**Comment by middaysan** [comment]
Solution `processPool = pbzip2.CreateConcurrencyPool(4) //  4 concurrent compressors` doesn't work :( 
[profile-16.pb.gz](https://github.com/cosnicolaou/pbzip2/files/11754766/profile-16.pb.gz)

pbzip2 800mb in ram

**Comment by cosnicolaou** [comment]
Can you share the code you used for this?

**Comment by cosnicolaou** [comment]
ok, so I took a look at this and everything seems to work as I'd expect. I called your function 10 times on a largish bzip2 file using all available cores on a mac and a linux server (ubuntu). After the 10 iterations I verified that using ```debug.SetGCPercent(10)``` or ```runtime.GC()``` causes the memory to be freed (both via looking at the profile and via memstats). Note that without the runtime.GC() or SetGCPercent() an idle server will hold on to the memory until it's needed by something else. Did you try either debug.SetGCPercent or runtime.GC?

**Comment by middaysan** [comment]
Yes, I tried using runtime.GC() and it didn't work. I mentioned this in the main message. Yesterday, I reintroduced runtime.GC() and initiated the server. I have attached the file that I received.

[profile 23.06.23 .pb.gz](https://github.com/cosnicolaou/pbzip2/files/11846852/profile.23.06.23.pb.gz)

**Comment by middaysan** [comment]
This is code that call unBzip2() func and where I use runtime.GC() after that

```golang
func unpack(archiveDst, unpackDst string) error {
	var err error
	switch filepath.Ext(archiveDst) {
	case ".zip":
		err = unzip(archiveDst, unpackDst)
	case ".bz2", ".tbz2":
		err = unBzip2(archiveDst, unpackDst)
		runtime.GC()
	default:
		err = errors.New("provider: Unsupported file type for file:" + archiveDst)
	}

	return err
}
```

**Comment by klauspost** [comment]
I think the issue is quite hard to nail without a complete standalone reproducer.

My intuition is that the decoder is stuck since not all content is read from the input and therefore keeping buffers referenced in a goroutine.

Since you are seeing lockups when limiting the number of inflight buffers that seems to confirm it.

**Comment by cosnicolaou** [comment]
On Fri, Jun 23, 2023 at 4:11 AM Klaus Post ***@***.***> wrote:

> I think the issue is quite hard to nail without a complete standalone
> reproducer.
>
Agreed! The rest of this response is directed to Anton:

I wonder if the problem is data-dependent. Can you send some example files
that are in flight when this problem occurs?

If it is getting stuck, then a stack trace of all active goroutines (via
sigquit for example) would be very useful.

Can you log the filename, size of the file before calling unbzip2, and the
filename and time to complete the operation for each file processed?
In addition, you should keep track of how many concurrent operations there
(eg. using an atomic counter), and when it's zero and stays zero for some
seconds, then dump a stack trace and memory profile. The only time
runtime.GC will have any effect is when your server is idle.

The fact that the memory is shown as belonging to io.ReadAll with called
functions suggests that the decompressor has finished; normally, you would
see bzip2.NewBlockReader as a child of decompress along with io.ReadAll. I
only ever see this when my test server is idle, and it goes away when GC
runs, but I don't really understand how this could be happening otherwise.

Sorry for the hassle!

Cheers, Cos.

My intuition is that the decoder is stuck since not all content is read
> from the input and therefore keeping buffers referenced in a goroutine.
>
Since you are seeing lockups when limiting the number of inflight buffers

**Comment by middaysan** [comment]
Could it help? 

I wrote sample project, https://github.com/middaysan/pbzip2-demo

I tried this on my mac m1 pro this simple code, and got next results:
- after 4 unpacks: 
[after 4 unpacks.gz](https://github.com/cosnicolaou/pbzip2/files/11882997/after.4.unpacks.gz)

- after 24 unpacks: 
[after 20 unpacks.gz](https://github.com/cosnicolaou/pbzip2/files/11882999/after.20.unpacks.gz)

- after 124 unpacks: 
[after 124 unpacks.gz](https://github.com/cosnicolaou/pbzip2/files/11883005/after.124.unpacks.gz)

As you see after 124 unpacks I had around 300 Mb ram used

How I took this results with my code:
1 `make run` and wait when out -> 'Server started'
2 `make unpack4`
3 `make report`
4 `make unpack20`
5 `make report`

Additional I tried to do 100 unpacks and run `make unpack4` 5 times

**Comment by klauspost** [comment]
Modified it slightly to eliminate disk writes: [main.go.gz](https://github.com/cosnicolaou/pbzip2/files/11883695/main.go.gz) and print goroutines.

I do not see anything leaking. I suspect your file system is locking up on writes, so requests never finish. Could you check that the code above keeps running to 100 with only one goroutine?

Since you have the profiles enabled, could you grab active goroutines when you observe the leak?

**Comment by middaysan** [comment]
Your modifications work without any leaks. But I tested my code (which includes writing to disk) inside the following Docker images(before this you should change `gtar` to `tar` inside my code):
- golang:1.21-rc-alpine3.17
- golang:1.21-rc-bullseye

This is really strange, that when I pass the ctx into the library and using the cancel function on ctx, but it isn't close goroutines. However, this solution doesn't seem to work unless the system exhibits specific disk-related behavior.


I expected that library should have the expected outcome that should be consistent regardless of the system it operates on. If there is an error, then library should return an error instead of unpacking all files correctly and have hidden behavior.

And what I have to do with that? Should I modify the system behavior? Or should I avoid writing data to disk? I don't understand :(

**Comment by klauspost** [comment]
> I expected that library should have the expected outcome that should be consistent regardless of the system it operates on.

If the `os.Create`, `io.Copy` or similar gets stuck the context is never canceled since unBzip2 never returns.

The library can't just terminate its operation just because it isn't used for a while.

You can send the `req.Context()` which will cancel the bzip2 operation when the request disconnects. But you will still have the operations above leaking - so you really need to figure out why your disk ops are hanging.

**Comment by middaysan** [comment]
Ok, thank you for your help.
