### ISSUE TITLE
Using the reader from pbzip2.NewReader, encounter hang

### ISSUE THREAD

**Issue by usuallyvexed** [cosnicolaou/pbzip2#33]
V1.0.2 compiled with with GO v1.21.1 or 1.21.2 

Attempting to decompress and extract a bzip2 compressed tarball which appears to have an error. The problem is that the entire program hangs. The file in question has the following error reported using bzip2 -tvv:

 srhires.231006.070514.0934:
    [1: huff+mtf rt+rld]
    [2: huff+mtf data integrity (CRC) error in data

If I try this snippet of code using the compress/bzip2 package that comes with GO:

ioSources[formatIndex+1] = bzip2.NewReader(ioSources[formatIndex])
n, cerr := io.Copy(io.Discard, ioSources[formatIndex+1])
fmt.Printf("Copy Error: %v\n", cerr)

The error returned is: bzip2 data invalid: origPtr out of bounds

Now if I try the same snippet with the pbzip2 reader:

ctx := context.Background()
ioSources[formatIndex+1] = pbzip2.NewReader(ctx, ioSources[formatIndex])
**_n, cerr := io.Copy(io.Discard, ioSources[formatIndex+1])_** <<< Hangs on this command!
fmt.Printf("Copy Error: %v\n", cerr)

the process hangs in the io.COPY statement.

Thank you.

**Comment by cosnicolaou** [comment]
Can you share your code and the problematic file please?

**Comment by usuallyvexed** [comment]
[pbzip2-hang.zip](https://github.com/cosnicolaou/pbzip2/files/12838372/pbzip2-hang.zip)
The zip contains a go reproducer and 2 input files, one good and one bad.
The problem occurs on both windows and linux. And the hang is erratic in occurrence, so you may have try several times. The reproducer will take the file name as a command line argument.

Hope this helps. 

And thank you.

**Comment by cosnicolaou** [comment]
I have a fix for this. Is it ok to include your bad test input in this repo as an ongoing test case?

**Comment by usuallyvexed** [comment]
Thank you for the fix!

As for the bad data, I would prefer that you not place it in the repo. And if possible remove the zip file from this conversation as well, please. You may keep the zip and data, just not publicly. Thank you.

**Comment by cosnicolaou** [comment]
Ok, I've deleted the post with the zip file.

**Comment by usuallyvexed** [comment]
Thank you for that, very much appreciated.
Also, I should have asked, when will the fix be available?
Thank you again for all of your efforts!

**Comment by cosnicolaou** [comment]
It's already merged and available as 1.0.3.

Cheers, Cos.

**Comment by usuallyvexed** [comment]
Nice!
