### ISSUE TITLE
Handling of false block splits

### ISSUE THREAD

**Issue by klauspost** [cosnicolaou/pbzip2#4]
> This case could be handled by adding support for ignoring specific instances of the magic numbers, but for now, the assumption is made that this is rare enough to be safely ignored.

Finding 6 bytes, 48 bits in random data would be 1 in 2^48, so once every 281.5 TB if all are aligned. 

Since you search for different alignments that is (if my math is correct) once every 35.18 TB. 

For me to be able to use this package, that isn't rare enough, since our users often scan terabytes of data. 

Have you looked into hardening this, and maybe have fallback to recombining on false splits?

**Comment by cosnicolaou** [comment]
Let me take a look later today, and yes, I'm sure there's something that can be done. Given that it's a rare event I'd let it happen and then attempt to remerge if the format fails to validate or something like that.

As an aside, have you used this package at all yet?

**Comment by cosnicolaou** [comment]
FYI, I also just realized that the tests fail with versions of go > 1.13. Let me figure that out too.

**Comment by klauspost** [comment]
@cosnicolaou 

> As an aside, have you used this package at all yet?

I would like to integrate it into [minio server](https://github.com/minio/minio/blob/master/internal/s3select/progress.go#L124) which allows to run serverside queries on JSON or CSV input. The stdlib bzip2 is horribly slow and it is used by quite a few people.

**Comment by cosnicolaou** [comment]
I have the merging working now. It can handle a single false positive within a single bzip block, which means it requires two magic number collisions in about a MB of data to be defeated which should be good enough for even the most demanding of applications. If that's not sufficient then falling back to the serial version would be the next logical thing to do.
